services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./static:/app/static
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - postgres

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - my_twitter/.env
    volumes:
      - ./static:/app/static
    command: >
      sh -c "
        /wait-for-it.sh postgres:5432 --timeout=60 --strict -- \
        alembic upgrade head &&
        uvicorn main:app --host 0.0.0.0 --port 8000
      "

  postgres:
    image: postgres:17.5
    environment:
      POSTGRES_DB: diploma
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: qwerty
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
